Bugfix: Modal not open/close on btn click. jQuery issue. Googled error message in console: "Uncaught TypeError: url.indexOf is not a function at jQuery.fn.init.jQuery.fn.load" Found http://stackoverflow.com/a/37915907/175882 : .load, .unload, and .error, deprecated since jQuery 1.8. Use .on() to register listeners.
modified:   app/assets/scripts/modules/StickyHeader.js